name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - "v*"

jobs:
  build:
    name: Build Package And Website
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Build package
        run: |
          pnpm install
          pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Build website
        working-directory: ${{github.workspace}}/docs
        run: |
          pnpm install
          pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: docs/.vitepress/dist
          include-hidden-files: true
          if-no-files-found: error

  deploy-to-gh-pages:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
          keep_history: false
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
